import cv2
import numpy as np
from pathlib import Path

def raster_to_svg(image_path: Path, output_path: Path, color_mode: str = "monochrome", threshold: int = 128) -> bool:
    """
    Traces raster image contours to true SVG vector paths.
    color_mode: 'monochrome' or 'color'
    """
    img = cv2.imread(str(image_path))
    if img is None:
        raise ValueError(f"Could not load image: {image_path}")

    h, w = img.shape[:2]
    
    if color_mode == "monochrome":
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        # Binary threshold
        _, thresh = cv2.threshold(gray, threshold, 255, cv2.THRESH_BINARY_INV)
        
        # Find contours
        contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS)
        
        svg_paths = []
        for cnt in contours:
            if cv2.contourArea(cnt) < 10:  # Skip noise
                continue
            # Approximate polygon
            epsilon = 0.005 * cv2.arcLength(cnt, True)
            approx = cv2.approxPolyDP(cnt, epsilon, True)
            
            pts = approx.reshape(-1, 2)
            if len(pts) < 3:
                continue
            
            d = f"M {pts[0][0]} {pts[0][1]} "
            for pt in pts[1:]:
                d += f"L {pt[0]} {pt[1]} "
            d += "Z"
            svg_paths.append(f'<path d="{d}" fill="#000000" fill-rule="evenodd" />')

        svg_content = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">
<!-- Generated by Convert.id Vectorizer -->
<rect width="100%" height="100%" fill="none"/>
{''.join(svg_paths)}
</svg>'''

    else:
        # Multi-layer color quantization
        # Reduce colors using k-means
        data = np.float32(img.reshape((-1, 3)))
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
        K = 8
        _, labels, centers = cv2.kmeans(data, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
        centers = np.uint8(centers)
        segmented = centers[labels.flatten()].reshape(img.shape)

        svg_paths = []
        for i, color in enumerate(centers):
            # Mask for this color
            mask = cv2.inRange(segmented, color, color)
            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            
            hex_color = "#{:02x}{:02x}{:02x}".format(color[2], color[1], color[0])
            for cnt in contours:
                if cv2.contourArea(cnt) < 15:
                    continue
                epsilon = 0.006 * cv2.arcLength(cnt, True)
                approx = cv2.approxPolyDP(cnt, epsilon, True)
                pts = approx.reshape(-1, 2)
                if len(pts) < 3:
                    continue
                d = f"M {pts[0][0]} {pts[0][1]} "
                for pt in pts[1:]:
                    d += f"L {pt[0]} {pt[1]} "
                d += "Z"
                svg_paths.append(f'<path d="{d}" fill="{hex_color}" opacity="0.95" />')

        svg_content = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">
<!-- Generated by Convert.id Color Vectorizer -->
{''.join(svg_paths)}
</svg>'''

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(svg_content)

    return True
